export const DASHBOARD = 'Dashboard'
export const USER = 'User'
export const ORDERS = 'Orders'
export const COUPON = 'Coupon'
export const CATEGORY = 'Category'
export const PRODUCT = 'Product'
export const ADD = 'Add'
export const LOGIN = 'Login'

export const ADD_PRODUCTS = 'Products'