export const DASHBOARD = 'Dashboard'
export const USER = 'User'
export const ORDERS = 'Orders'
export const COUPON = 'Coupon'
export const CATEGORY = 'Category'
export const PRODUCT = 'Product'
export const ADD = 'Add'
export const LOGIN = 'Login'
export const TOKEN = 'token'
export const LOGOUT = 'Logout'

export const ADD_PRODUCTS = 'Products'
export const ADD_COUPONS = 'Coupons'
export const ADD_ORDERS = 'Orders'
export const ADD_BANNER = 'Banner'
export const ADD_SIZE_OPTION = 'Size Option'
export const ADD_CATEGORIES = 'Categories'